[project]
name = "gdos-zanieczyszczenia"
version = "0.1.0"
description = "Analiza danych o zanieczyszczeniach z GDOŚ"
authors = [
    {name = "kamyk"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "xlrd (>=2.0.2,<3.0.0)",
    "pandas (>=3.0.0,<4.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "pyproj (>=3.7.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
